[package]
name = "doctown"
version = "9.0.0"
edition = "2024"

[dependencies]
ollama-rs = { version = "0.3.3", features = ["stream"] }
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
